1D Array

In [2]:
import numpy as np
a1 = np. array ([10.5,11.1,13.2,11])
type(a1)

numpy.ndarray

In [3]:
a1

array([10.5, 11.1, 13.2, 11. ])

In [4]:
a1.ndim

1

In [5]:
a1.shape

(4,)

In [6]:
type(a1)

numpy.ndarray

In [7]:
a2= ([10.2,20,30.6])
type(a2)

list

In [10]:
b2= np.array(a1)
b2

array([10.5, 11.1, 13.2, 11. ])

In [13]:
a3=([20.2,40.2,60.3])
type(a3)

list

In [14]:
b3 = np.array(a3)
b3

array([20.2, 40.2, 60.3])

2D Array

In [17]:
a4 = [[1,5,3],
             [5,6,7]]
type(a4)


list

In [18]:
b4 = np.array(a4)


In [19]:
b4

array([[1, 5, 3],
       [5, 6, 7]])

In [20]:
b4.ndim

2

In [21]:
b4.shape

(2, 3)

3D Array.

In [22]:
b5 = [[ [ 2,5,6],
       [6,5,6]],
        

[[7,5,6],
      [8,6,7]],
[[10,50,60],
 [50,80,90]]]

 
       

In [23]:
type(b5)

list

In [24]:
c1 = np.array(b5)

In [25]:
c1

array([[[ 2,  5,  6],
        [ 6,  5,  6]],

       [[ 7,  5,  6],
        [ 8,  6,  7]],

       [[10, 50, 60],
        [50, 80, 90]]])

In [26]:
c1.ndim

3

In [27]:
c1.shape

(3, 2, 3)

In [28]:
a10 = [20,10,50]
type(a10)

list

In [30]:
a11 =[]
for i in a10:

    a11 .append(i*3)


In [31]:
a11

[60, 30, 150]

In [32]:
 a10

[20, 10, 50]

In [33]:
a12= np.array(a10)


In [34]:
a12

array([20, 10, 50])

In [37]:
a13= 3*a12
a13

array([ 60,  30, 150])

In [38]:
list2 =[100,500,600]
list3 = np.array(list2)
list3

array([100, 500, 600])

In [40]:
list4 = 4+list3
list4


array([104, 504, 604])

In [42]:
list5 = 1.5*list3
list5

array([150., 750., 900.])

## get the product of all number inside the list vs array.

In [45]:
p1 = [2,5]
type(p1)

list

In [48]:
p = 1

for i in p1:
    p = p *i

    

In [49]:
p

10

In [50]:
np.prod(p1)

np.int64(10)

Numpy aggregation

In [53]:
 agg = [50,60,70]

 agg

[50, 60, 70]

In [54]:
np.sum(agg)

np.int64(180)

In [55]:
np.mean(agg)

np.float64(60.0)

In [56]:
np.median(agg)

np.float64(60.0)

In [57]:
np.max(agg)

np.int64(70)

In [58]:
np.min(agg)

np.int64(50)

In [59]:
np.prod(agg)

np.int64(210000)

## MATHMETICAL FUNCTION.
1.EXP.
2.LOG
3. SIN
4.COS
5.TAN
6.1RAD = PI /180deg

#

In [60]:
np.exp(1)

np.float64(2.718281828459045)

Range(start,stop,step)

In [61]:
list(range(5,50,2))

[5,
 7,
 9,
 11,
 13,
 15,
 17,
 19,
 21,
 23,
 25,
 27,
 29,
 31,
 33,
 35,
 37,
 39,
 41,
 43,
 45,
 47,
 49]

In [62]:
list(range(3,10,2))

[3, 5, 7, 9]

In [63]:
list(range(10.2,10.6,1.1))

TypeError: 'float' object cannot be interpreted as an integer

In [65]:
a  = np.arange(1.1,1.5,0.1)

In [66]:
a

array([1.1, 1.2, 1.3, 1.4])

In [67]:
b = np.arange(1.1, 100,0.1)

In [68]:
b

array([ 1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,  2.1,
        2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,  3.2,
        3.3,  3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ,  4.1,  4.2,  4.3,
        4.4,  4.5,  4.6,  4.7,  4.8,  4.9,  5. ,  5.1,  5.2,  5.3,  5.4,
        5.5,  5.6,  5.7,  5.8,  5.9,  6. ,  6.1,  6.2,  6.3,  6.4,  6.5,
        6.6,  6.7,  6.8,  6.9,  7. ,  7.1,  7.2,  7.3,  7.4,  7.5,  7.6,
        7.7,  7.8,  7.9,  8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,
        8.8,  8.9,  9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,
        9.9, 10. , 10.1, 10.2, 10.3, 10.4, 10.5, 10.6, 10.7, 10.8, 10.9,
       11. , 11.1, 11.2, 11.3, 11.4, 11.5, 11.6, 11.7, 11.8, 11.9, 12. ,
       12.1, 12.2, 12.3, 12.4, 12.5, 12.6, 12.7, 12.8, 12.9, 13. , 13.1,
       13.2, 13.3, 13.4, 13.5, 13.6, 13.7, 13.8, 13.9, 14. , 14.1, 14.2,
       14.3, 14.4, 14.5, 14.6, 14.7, 14.8, 14.9, 15. , 15.1, 15.2, 15.3,
       15.4, 15.5, 15.6, 15.7, 15.8, 15.9, 16. , 16

In [69]:
b+2

array([  3.1,   3.2,   3.3,   3.4,   3.5,   3.6,   3.7,   3.8,   3.9,
         4. ,   4.1,   4.2,   4.3,   4.4,   4.5,   4.6,   4.7,   4.8,
         4.9,   5. ,   5.1,   5.2,   5.3,   5.4,   5.5,   5.6,   5.7,
         5.8,   5.9,   6. ,   6.1,   6.2,   6.3,   6.4,   6.5,   6.6,
         6.7,   6.8,   6.9,   7. ,   7.1,   7.2,   7.3,   7.4,   7.5,
         7.6,   7.7,   7.8,   7.9,   8. ,   8.1,   8.2,   8.3,   8.4,
         8.5,   8.6,   8.7,   8.8,   8.9,   9. ,   9.1,   9.2,   9.3,
         9.4,   9.5,   9.6,   9.7,   9.8,   9.9,  10. ,  10.1,  10.2,
        10.3,  10.4,  10.5,  10.6,  10.7,  10.8,  10.9,  11. ,  11.1,
        11.2,  11.3,  11.4,  11.5,  11.6,  11.7,  11.8,  11.9,  12. ,
        12.1,  12.2,  12.3,  12.4,  12.5,  12.6,  12.7,  12.8,  12.9,
        13. ,  13.1,  13.2,  13.3,  13.4,  13.5,  13.6,  13.7,  13.8,
        13.9,  14. ,  14.1,  14.2,  14.3,  14.4,  14.5,  14.6,  14.7,
        14.8,  14.9,  15. ,  15.1,  15.2,  15.3,  15.4,  15.5,  15.6,
        15.7,  15.8,

In [70]:
b**3

array([1.33100000e+00, 1.72800000e+00, 2.19700000e+00, 2.74400000e+00,
       3.37500000e+00, 4.09600000e+00, 4.91300000e+00, 5.83200000e+00,
       6.85900000e+00, 8.00000000e+00, 9.26100000e+00, 1.06480000e+01,
       1.21670000e+01, 1.38240000e+01, 1.56250000e+01, 1.75760000e+01,
       1.96830000e+01, 2.19520000e+01, 2.43890000e+01, 2.70000000e+01,
       2.97910000e+01, 3.27680000e+01, 3.59370000e+01, 3.93040000e+01,
       4.28750000e+01, 4.66560000e+01, 5.06530000e+01, 5.48720000e+01,
       5.93190000e+01, 6.40000000e+01, 6.89210000e+01, 7.40880000e+01,
       7.95070000e+01, 8.51840000e+01, 9.11250000e+01, 9.73360000e+01,
       1.03823000e+02, 1.10592000e+02, 1.17649000e+02, 1.25000000e+02,
       1.32651000e+02, 1.40608000e+02, 1.48877000e+02, 1.57464000e+02,
       1.66375000e+02, 1.75616000e+02, 1.85193000e+02, 1.95112000e+02,
       2.05379000e+02, 2.16000000e+02, 2.26981000e+02, 2.38328000e+02,
       2.50047000e+02, 2.62144000e+02, 2.74625000e+02, 2.87496000e+02,
      

In [71]:
11.0*b

array([  12.1,   13.2,   14.3,   15.4,   16.5,   17.6,   18.7,   19.8,
         20.9,   22. ,   23.1,   24.2,   25.3,   26.4,   27.5,   28.6,
         29.7,   30.8,   31.9,   33. ,   34.1,   35.2,   36.3,   37.4,
         38.5,   39.6,   40.7,   41.8,   42.9,   44. ,   45.1,   46.2,
         47.3,   48.4,   49.5,   50.6,   51.7,   52.8,   53.9,   55. ,
         56.1,   57.2,   58.3,   59.4,   60.5,   61.6,   62.7,   63.8,
         64.9,   66. ,   67.1,   68.2,   69.3,   70.4,   71.5,   72.6,
         73.7,   74.8,   75.9,   77. ,   78.1,   79.2,   80.3,   81.4,
         82.5,   83.6,   84.7,   85.8,   86.9,   88. ,   89.1,   90.2,
         91.3,   92.4,   93.5,   94.6,   95.7,   96.8,   97.9,   99. ,
        100.1,  101.2,  102.3,  103.4,  104.5,  105.6,  106.7,  107.8,
        108.9,  110. ,  111.1,  112.2,  113.3,  114.4,  115.5,  116.6,
        117.7,  118.8,  119.9,  121. ,  122.1,  123.2,  124.3,  125.4,
        126.5,  127.6,  128.7,  129.8,  130.9,  132. ,  133.1,  134.2,
      

In [72]:
b**(1/2)

array([1.04880885, 1.09544512, 1.14017543, 1.18321596, 1.22474487,
       1.26491106, 1.30384048, 1.34164079, 1.37840488, 1.41421356,
       1.44913767, 1.4832397 , 1.51657509, 1.54919334, 1.58113883,
       1.61245155, 1.64316767, 1.67332005, 1.70293864, 1.73205081,
       1.76068169, 1.78885438, 1.81659021, 1.84390889, 1.87082869,
       1.8973666 , 1.92353841, 1.94935887, 1.97484177, 2.        ,
       2.02484567, 2.04939015, 2.07364414, 2.0976177 , 2.12132034,
       2.14476106, 2.16794834, 2.19089023, 2.21359436, 2.23606798,
       2.25831796, 2.28035085, 2.30217289, 2.32379001, 2.34520788,
       2.36643191, 2.38746728, 2.40831892, 2.42899156, 2.44948974,
       2.46981781, 2.48997992, 2.50998008, 2.52982213, 2.54950976,
       2.56904652, 2.58843582, 2.60768096, 2.62678511, 2.64575131,
       2.66458252, 2.68328157, 2.70185122, 2.7202941 , 2.73861279,
       2.75680975, 2.77488739, 2.79284801, 2.81069386, 2.82842712,
       2.84604989, 2.86356421, 2.88097206, 2.89827535, 2.91547

linspace- its give same range.

In [73]:
line = np.linspace(1,10,4)

In [74]:
line

array([ 1.,  4.,  7., 10.])

In [76]:
line2 = np.linspace(2,20,10)
line2

array([ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

In [77]:
line2.shape

(10,)

## generate random number betwenn 1 to 10


In [80]:
np.random.random()

0.16639244224705496

In [84]:
ran = np .random.random(10)
ran

array([0.94158672, 0.3614382 , 0.8528865 , 0.36126275, 0.42115696,
       0.12637081, 0.30541334, 0.54132194, 0.85550041, 0.5066807 ])

## geneerate random integer number.

In [90]:
 np.random.randint(low =1, high= 5)

3

In [ ]:
intnum = np.random.randint(low = 1, high = 10 , size = 100)
intnum


array([1, 4, 7, 3, 4, 5, 4, 7, 9, 4, 8, 7, 8, 5, 3, 8, 2, 7, 7, 5, 2, 3,
       2, 1, 6, 1, 2, 4, 9, 5, 9, 2, 1, 7, 4, 5, 4, 8, 6, 5, 5, 7, 2, 4,
       7, 5, 4, 9, 2, 8, 8, 5, 5, 2, 2, 1, 8, 6, 2, 9, 4, 6, 4, 1, 7, 1,
       6, 9, 5, 8, 8, 2, 4, 4, 6, 4, 1, 8, 6, 7, 1, 1, 4, 7, 7, 3, 5, 9,
       7, 1, 8, 1, 8, 6, 4, 4, 4, 6, 4, 1], dtype=int32)

# normally distribute variable mean = 10 , and std= 1

In [108]:
n1=np.random.normal( loc = 10, scale = 1)

n1




9.758965544563807

In [111]:
import seaborn as sns
sns.histplot(n1, kde = True)

TypeError: object of type 'float' has no len()