## multithreading
1.single thread works on one tasks at a time.
2.mulit threading if you want to work on multiple tasks simulatenously.

In [1]:
import time

In [2]:
%time
time.sleep(2)
print("example")
time.sleep(3)
print("hello")

CPU times: total: 0 ns
Wall time: 12.2 μs
example
hello


In [4]:
%%time
time.sleep(1)

print("hello")
time.sleep(1)
print("morning")

hello
morning
CPU times: total: 15.6 ms
Wall time: 2.07 s


In [5]:
def simple_interest(p,n,r):
    print("simple interest calculation start")
    i = (p*n*r)/100
    a = i+p
    print(f"simple interest:{i:.2f}INR")
    print(f"amount :{a:.2f}INR")
    print(f"function is completed")


In [6]:
simple_interest(1000,5,4.2)

simple interest calculation start
simple interest:210.00INR
amount :1210.00INR
function is completed


In [7]:
%%time
simple_interest(p= 200, n =3 , r= 6.3)

simple interest calculation start
simple interest:37.80INR
amount :237.80INR
function is completed
CPU times: total: 0 ns
Wall time: 474 μs


In [13]:

def hypro(a,b):
    print("start assign value:")
    time.sleep(2)
    c = (a**2 + b**2)**(1/2)
    print(f"finally fuction  {a} and {b}:{c:.4f}INR")
    print(f"task completed")


In [15]:
%%time
hypro(4,7)

start assign value:
finally fuction  4 and 7:8.0623INR
task completed
CPU times: total: 15.6 ms
Wall time: 2 s


In [16]:
from threading import Thread

In [19]:
## create thread and start its.
th1 =Thread(target=simple_interest,args=(400,2,3.2))
th2 = Thread(target = hypro,args=(2,3))

print(f"start thread")
th1.start()
th2.start()

# join thread
th1.join()
th2.join()

start thread
simple interest calculation start
simple interest:25.60INR
amount :425.60INR
function is completed
start assign value:
finally fuction  2 and 3:3.6056INR
task completed


single function but multiple value to calculate

In [20]:
def square(n):
    time.sleep(1)
    s = n**2
    print(f"square of number {n } is {s}\n \n")

In [21]:
%%time
square(5)


square of number 5 is 25
 

CPU times: total: 0 ns
Wall time: 1 s


In [22]:
def min(n1,n2):
    time.sleep(1)
    minus = n1- n2
    print(f"minus of {n1} and {n2} ,{minus:.2f}")

In [24]:
%%time
min(5,3)

minus of 5 and 3 ,2.00
CPU times: total: 15.6 ms
Wall time: 1 s


In [25]:
a=[10,20,30]

In [27]:
%%time
for i in a:
    square(i)


square of number 10 is 100
 

square of number 20 is 400
 

square of number 30 is 900
 

CPU times: total: 0 ns
Wall time: 3.01 s


In [32]:
## if i want to assign list in function.
def div(n3,n4):
    time.sleep(1)
    division= n3/n4
    print(f"number of values {n3} and {n4} :{division:.2f}")

In [33]:
%%time
div(10,5)

number of values 10 and 5 :2.00
CPU times: total: 0 ns
Wall time: 1.01 s


## create thread for square ..

In [49]:
def square_mul(b:list):
    # create thread.
    threads =[]
    for i in b:
      
      th = Thread(target=square, args=(i,))
      th.start()
    threads.append(th)
    for th in threads:
      th.join()


In [50]:
b1 = [10,20,30]

In [51]:
b1

[10, 20, 30]

In [52]:
%%time
square_mul(b1)

square of number 10 is 100
 

square of number 20 is 400
 

square of number 30 is 900
 

CPU times: total: 15.6 ms
Wall time: 1.16 s


In [53]:
import numpy as np

In [55]:
list1 = np.arange(1,20, 1)
list1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [ ]:
%%time
square_mul(list1)


square of number 1 is 1
 

square of number 2 is 4
 

square of number 3 is 9
 

square of number 4 is 16
 

square of number 5 is 25
 

square of number 6 is 36
 

square of number 7 is 49
 

square of number 8 is 64
 

square of number 9 is 81
 

square of number 10 is 100
 

square of number 11 is 121
 

square of number 12 is 144
 

square of number 13 is 169
 

square of number 15 is 225
 

square of number 14 is 196
 

square of number 16 is 256
 
square of number 19 is 361
 

CPU times: total: 46.9 ms
Wall time: 3.26 s

square of number 18 is 324
 



square of number 17 is 289
 



In [58]:
array2 = np.arange(20,1000,2)
array2

array([ 20,  22,  24,  26,  28,  30,  32,  34,  36,  38,  40,  42,  44,
        46,  48,  50,  52,  54,  56,  58,  60,  62,  64,  66,  68,  70,
        72,  74,  76,  78,  80,  82,  84,  86,  88,  90,  92,  94,  96,
        98, 100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122,
       124, 126, 128, 130, 132, 134, 136, 138, 140, 142, 144, 146, 148,
       150, 152, 154, 156, 158, 160, 162, 164, 166, 168, 170, 172, 174,
       176, 178, 180, 182, 184, 186, 188, 190, 192, 194, 196, 198, 200,
       202, 204, 206, 208, 210, 212, 214, 216, 218, 220, 222, 224, 226,
       228, 230, 232, 234, 236, 238, 240, 242, 244, 246, 248, 250, 252,
       254, 256, 258, 260, 262, 264, 266, 268, 270, 272, 274, 276, 278,
       280, 282, 284, 286, 288, 290, 292, 294, 296, 298, 300, 302, 304,
       306, 308, 310, 312, 314, 316, 318, 320, 322, 324, 326, 328, 330,
       332, 334, 336, 338, 340, 342, 344, 346, 348, 350, 352, 354, 356,
       358, 360, 362, 364, 366, 368, 370, 372, 374, 376, 378, 38

In [59]:
array3 = np.arange(100,2000,3)
array3

array([ 100,  103,  106,  109,  112,  115,  118,  121,  124,  127,  130,
        133,  136,  139,  142,  145,  148,  151,  154,  157,  160,  163,
        166,  169,  172,  175,  178,  181,  184,  187,  190,  193,  196,
        199,  202,  205,  208,  211,  214,  217,  220,  223,  226,  229,
        232,  235,  238,  241,  244,  247,  250,  253,  256,  259,  262,
        265,  268,  271,  274,  277,  280,  283,  286,  289,  292,  295,
        298,  301,  304,  307,  310,  313,  316,  319,  322,  325,  328,
        331,  334,  337,  340,  343,  346,  349,  352,  355,  358,  361,
        364,  367,  370,  373,  376,  379,  382,  385,  388,  391,  394,
        397,  400,  403,  406,  409,  412,  415,  418,  421,  424,  427,
        430,  433,  436,  439,  442,  445,  448,  451,  454,  457,  460,
        463,  466,  469,  472,  475,  478,  481,  484,  487,  490,  493,
        496,  499,  502,  505,  508,  511,  514,  517,  520,  523,  526,
        529,  532,  535,  538,  541,  544,  547,  5

In [60]:
%%time
square_mul(array3)

square of number 100 is 10000
 

square of number 103 is 10609
 

square of number 106 is 11236
 

square of number 109 is 11881
 

square of number 112 is 12544
 

square of number 115 is 13225
 

square of number 118 is 13924
 

square of number 121 is 14641
 

square of number 124 is 15376
 

square of number 127 is 16129
 

square of number 130 is 16900
 

square of number 133 is 17689
 

square of number 136 is 18496
 

square of number 139 is 19321
 

square of number 142 is 20164
 

square of number 145 is 21025
 

square of number 148 is 21904
 

square of number 151 is 22801
 

square of number 154 is 23716
 

square of number 157 is 24649
 

square of number 160 is 25600
 

square of number 163 is 26569
 

square of number 166 is 27556
 

square of number 169 is 28561
 

square of number 172 is 29584
 

square of number 175 is 30625
 

square of number 178 is 31684
 

square of number 181 is 32761
 

square of number 184 is 33856
 

square of number 187 is 34969
 

square of 

In [61]:
urls =[
    "https://raw.githubusercontent.com/utkarshg1/mlproject_regression/main/artifacts/data.csv",
    "https://raw.githubusercontent.com/utkarshg1/mlproject_regression/main/artifacts/test.csv",
    "https://raw.githubusercontent.com/utkarshg1/mlproject_regression/main/artifacts/train.csv"
]

In [62]:
urls[0]

'https://raw.githubusercontent.com/utkarshg1/mlproject_regression/main/artifacts/data.csv'

In [63]:
urls[0].split("/")

['https:',
 '',
 'raw.githubusercontent.com',
 'utkarshg1',
 'mlproject_regression',
 'main',
 'artifacts',
 'data.csv']

In [64]:
urls[0].split("/")[-1]

'data.csv'

In [65]:
from urllib.request import urlretrieve

In [67]:
def download_file(url:str):
    filename = url.split("/")[-1]
    print(f"{filename} download start...")
    urlretrieve(url,filename)
    print(f"{filename} download complte")

In [68]:
urls

['https://raw.githubusercontent.com/utkarshg1/mlproject_regression/main/artifacts/data.csv',
 'https://raw.githubusercontent.com/utkarshg1/mlproject_regression/main/artifacts/test.csv',
 'https://raw.githubusercontent.com/utkarshg1/mlproject_regression/main/artifacts/train.csv']

In [70]:
%%time
for i in urls:
    download_file(i)
    

data.csv download start...
data.csv download complte
test.csv download start...
test.csv download complte
train.csv download start...
train.csv download complte
CPU times: total: 328 ms
Wall time: 3.17 s


In [71]:
def multithread_download(urls:list[str]):
    threads=[]
    for i in urls:
     th = Thread(target= download_file , args =(i,))
     th.start()
     threads.append(th)
     for th in threads:
        th.join()

In [72]:
%%time
multithread_download(urls)

data.csv download start...
data.csv download complte
test.csv download start...
test.csv download complte
train.csv download start...
train.csv download complte
CPU times: total: 188 ms
Wall time: 2.97 s
